climate:
  - platform: generic_thermostat
    name: master_vol
    heater: input_boolean.dummy1
    target_sensor: sensor.tmp_wohnzimmer_temperature
    min_temp: 0
    max_temp: 100
    precision: 1.0