night_off_automations:
  name: Night Off Automations
  entities:
    - automation.az_btn_dbl
    - automation.az_btn_trppl
    - automation.wz_btn_couch_single
    - automation.az_game_mode_trigger
    - automation.az_gamemode_trigger
    - automation.az_pc_state
    - automation.cf_bed
    - automation.new_automation_2
    - automation.notify_kaffeemaschine_vorbereitet
    - automation.pc_changeaudioinput
    - automation.tag_charging_bedroom_is_scanned
    - automation.wz_btn_bar_double
    - automation.wz_btn_bar_single
    - automation.wz_btn_couch_double
    - automation.wz_btn_couch_single
    - automation.wz_couch_btn_triple
    - automation.wz_overwrite_esstisch
    - automation.wz_overwrite_kuche
    - automation.wz_overwrite_wohnzimmer
    - automation.wz_shield