secrets: /config/secrets.yaml
appdaemon:
  internal_function_timeout: 30
  thread_duration_warning_threshold: 30
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret  elevation
  time_zone: !secret timezone
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin: null
api: null
hadashboard: null
