platform: androidtv
host: !secret shield_ip
name: Shield TV
adb_server_ip: !secret adb_ip
device_class: androidtv
adb_server_port: 5037
state_detection_rules:
  'com.amazon.tv.launcher':
    - 'standby'
  'com.netflix.ninja':
    - 'media_session_state'
  'com.ellation.vrv':
    - 'audio_state'
  'com.plexapp.android':
    - 'playing':
        'media_session_state': 3  # this indentation is important!
        'wake_lock_size': 3       # this indentation is important!
    - 'paused':
        'media_session_state': 3  # this indentation is important!
        'wake_lock_size': 1       # this indentation is important!
    - 'standby'
  'com.amazon.amazonvideo.livingroom':
    - 'playing':
        'wake_lock_size': 2
    - 'paused':
        'wake_lock_size': 0

