              action: call-service
              service: browser_mod.popup
              service_data:
                title: Information
                hide_header: true
                deviceID: this
                style:
                  .: |
                    :host .content {
                      width: calc(385px + 385px);
                      max-width: 90vw;
                    }
                  $: |
                    .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                      background: none !important;
                    }
                card:
                  type: custom:layout-card
                  column_num: 2
                  column_width: [385, 385]
                  layout: vertical
                  cards:
                    - type: entities
                      title: Home Assistant
                      class: add_header
                      show_header_toggle: false
                      entities:

                        - entity: sensor.hass_version

                        - entity: sensor.home_assistant_v2_db

                        - entity: sensor.home_assistant_log

                        - entity: sensor.hass_uptime
                            
                        - type: custom:mini-graph-card
                          entities:
                            - color: '#385581'
                              entity: sensor.speedtest_upload
                            - color: green
                              entity: sensor.speedtest_download
                          align_state: left
                          group: false
                          points_per_hour: 15
                          line_width: 3
                          hour24: true
                          hours_to_show: 1.5
                          show:
                            {fill: fade, icon: false, name: false, state: false, 
                            name_adaptive_color: true, labels: hover, legend: false}
                          tap_action:
                            action: none
                            
                        - type: custom:hui-element
                          card_type: horizontal-stack
                          style: &horizontal-style |
                            #root {
                              justify-content: space-evenly;
                              margin: 1.4em -0.7em 0.7em 0;
                            }
                          cards:
                          - type: custom:button-card
                            name: '<ha-icon icon="mdi:reload"></ha-icon> Home Assistant'
                            tap_action:
                              services: |
                                [[[ hass.callService('browser_mod', 'toast', {message: 'Restarting Home Assistant...'});
                                hass.callService('homeassistant', 'restart'); ]]]
                            template: name_action                           

                    - break

                    - type: entities
                      title: Synology NAS
                      class: add_header
                      show_header_toggle: false
                    #  style: |
                    #    #states > div > mini-graph-card {
                    #      margin: -22.7px -34px -21px -23px;
                    #    }
                      entities:

                        - entity: sensor.nas_status

                        - entity: sensor.ds1512_tobias_temperature

                        - type: custom:bar-card
                          width: 55%
                          height: 2em
                          decimal: 0
                          unit_of_measurement: '%'
                          positions: &bar_card_positions
                            icon: outside
                            indicator: 'off'
                            name: outside
                          severity: &bar_card_severity
                            - color: '#248042'
                              from: 0
                              to: 49
                            - color: '#e68f32'
                              from: 50
                              to: 89
                            - color: '#e63917'
                              from: 90
                              to: 100
                          entity_row: true
                          entities:
                            - entity: sensor.processor_use_percent
                              name: Processor
                              tap_action:
                                action: call-service
                                service: homeassistant.update_entity
                                service_data:
                                  entity_id: sensor.processor_use_percent

                            - entity: sensor.ds1512_tobias_memory_usage_real
                              name: Memory - 1GB
                              tap_action:
                                action: call-service
                                service: homeassistant.update_entity
                                service_data:
                                  entity_id: sensor.ds1512_tobias_memory_usage_real

                            - entity: sensor.ds1512_tobias_volume_1_volume_used
                              name: Storage - 14.4TB
                              tap_action:
                                action: call-service
                                service: homeassistant.update_entity
                                service_data:
                                  entity_id: sensor.ds1512_tobias_volume_1_volume_used

                        - type: custom:hui-element
                          card_type: horizontal-stack
                          cards:

                            - type: entities
                              class: information_network
                              entities:
                                - entity: sensor.ds1512_tobias_network_down
                                  style: ':host {--paper-item-icon-color: green;}'

                            - type: entities
                              class: information_network
                              entities:
                                - entity: sensor.ds1512_tobias_network_up
                                  style: ':host {--paper-item-icon-color: #385581;}'

                        - type: custom:mini-graph-card
                          entities:
                            - color: '#385581'
                              entity: sensor.ds1512_tobias_network_up
                            - color: green
                              entity: sensor.ds1512_tobias_network_down
                          align_state: left
                          group: false
                          points_per_hour: 15
                          line_width: 3
                          hour24: true
                          hours_to_show: 1.5
                          show:
                            {fill: fade, icon: false, name: false, state: false, 
                            name_adaptive_color: true, labels: hover, legend: false}
                          tap_action:
                            action: none
