              action: call-service
              service: browser_mod.popup
              service_data:
                title: Zolder
                deviceID: this
                card:
                  type: vertical-stack
                  cards:
                    - type: custom:mini-media-player
                      entity: media_player.zolder
                      source: icon
                      artwork: cover
                      hide:
                        power: true
                        icon: true
                      speaker_group:
                        platform: sonos
                        show_group_count: true
                        entities:
                          - entity_id: media_player.zolder
                            name: Zolder
                      shortcuts:
                        columns: 4
                        buttons:
                          - icon: mdi:speaker-wireless          
                            type: playlist
                            id: spotify:playlist:7BsRfcY90dc4OPxmyuhPYI
                          - icon: mdi:radio
                            type: source
                            id: "538 (Main)"
                          - icon: mdi:party-popper
                            type: source                      
                            id: "SLAM! 88.4 (Top-40-Pop muziek)"
                style:
                  '--ha-card-border-radius': 0vw 0vw 0.8vw 0.8vw
                  border-radius: 0.8vw
                  opacity: 0.9