
# Use this file to store secrets like usernames and passwords.
# Learn more at https: ""
name: ""
timezone: ""
latitude: ""
longitude: ""
elevation: ""
broker: ""
broker_port: ""
CLOUDMQTT_USER: ""
CLOUDMQTT_PASSWORD: ""
git_token: ""
spotify_id: ""
spotify_secret: ""
spotify_username: ""
spotify_password: ""
vacuum_token: ""
darksky_api: ""
janneckdenda_email_password: ""
janneckdenda_email: ""
google_client_id: ""
google_client_secret: ""
janneck_chat_id: ""
telegram_api: ""
edge_os_host: ""
edge_os_ssl: ""
edge_os_username: ""
edge_os_password: ""
ssl_certificate: ""
msapi: ""
twitch: ""
AFTERSHIP_APIKEY: ""
plex_url: ""
plex_port: ""
plex_api: ""
todoist_token: ""
pihole_token: ""
hacs_url: ""
primary_sp_dc: ""
primary_sp_key: ""
ip_r5: ""
mac_r5: ""
ip_unraid: ""
wz_fan_ip: ""
wz_fan_token: ""
nanoleaf_ip: ""
nanoleaf_token: ""
emby_host: ""
emby_token: ""
emby_id: ""
emby_port: ""
onkyo_ip: ""
shield_ip: ""
adb_ip: ""
rm_mini: ""
alarm_code: ""
octoprint_ip: ""
octoprint_key: ""
picnic_user: ""
picnic_pass: ""
frigate_url: ""
db_url: ""
sf_user: ""
sf_pass: ""
ender_cam: ""
wz_cam: ""
mail_user: ""
mail_password: ""
mail_server: ""
mail_port: ""