platform: broadlink
mac: !secret rm_mini
switches:
  - name: beamer_pow
    command_on: 'JgBQAAABKpMUERQQFRAVNRUQFBEUERQRFDYUNRURFBAVNBYQFRAUERQ2FDYUNhQRFBEUERQQFTUVEBUQFRAUNhQ2FDYUNhUQFAAFtgABL0gUAA0FAAAAAAAAAAA='
    command_off: 'JgBQAAABKpMUERQQFRAVNRUQFBEUERQRFDYUNRURFBAVNBYQFRAUERQ2FDYUNhQRFBEUERQQFTUVEBUQFRAUNhQ2FDYUNhUQFAAFtgABL0gUAA0FAAAAAAAAAAA='
  - name: beamer_hdmi
    command_on: 'JgBQAAABKpIVEBQRFBEUNhQQFRAVEBQRFDYUNhQRFBEUNhQRFBAVEBU1FRAVEBQ2FBEUERQ2FDYUERQ2FDYUERQ2FDYUEBUQFQAFuwABKkgUAA0FAAAAAAAAAAA='
  - name: klimaanlage
    command_on: 'JgDKAJCPEzQSERI1EhESERIREhETNBE1ExESERIREhESERM0EhESERI1EhESERE2EhESERIREjUSNBI1EjQSNBI1EjQTNBI0EjUSNBI1EjQSNBM0EjQTERI0ERISNRIREjQTERESEqqQkBIREjQTERI0EjQTNBI0ExESERI0EjUSNBI1EjQSERI1EjQSERI1EjQSERM0EjQSNRIREhESERMREhESERIREhETERESEhESERIRExESERIRETUSEhI0EhETNBIREjQTNBIADQUAAAAAAAAAAAAAAAAAAA=='
    command_off: 'JgDKAJGPEjUSERI0ExESERIRERISNRIREhEREhISEhESERE2ERIREhI0ExEREhI0ExESERIREjUSNBI0EzQSNBM0EjQTNBI0EzQSNBI1EjQSNRE1EjUSNBI1EhESNBMREjQREhISEqqPkRIREjQSERM0EjQTNBI0EhISNBI0EzQSNBM0EjQSEhI0EjQTERI0EjUSERE1EjUSNBIREhISERIREhESEhIRERIREhIREhISERESEhESERMRERISERE1ExERNRIREzQSNBIADQUAAAAAAAAAAAAAAAAAAA=='