  name: 'Baynesian Badezimmer'
  platform: 'bayesian'
  prior: 0.60
  probability_threshold: 0.80
  observations:
    - platform: 'state'
      entity_id: binary_sensor.0x00158d00036b9e63_occupancy
      prob_given_true: 0.90
      prob_given_false: 0.05
      to_state: 'on'
    - platform: 'numeric_state'
      entity_id: 'sensor.tmp_wz_humidity'
      prob_given_true: 0.95
      prob_given_false: 0.1
      above: 70
    - platform: 'state'
      entity_id: binary_sensor.duschen
      prob_given_true: 0.90
      prob_given_false: 0.1
      to_state: 'on'
    - platform: 'state'
      entity_id: binary_sensor.bathroom_dusche_last1
      prob_given_true: 0.90
      prob_given_false: 0.1
      to_state: 'on'
