  name: 'duschen'
  platform: 'bayesian'
  prior: 0.50
  probability_threshold: 0.80
  observations:
    - platform: 'state'
      entity_id: binary_sensor.door_shower_contact
      prob_given_true: 0.95
      prob_given_false: 0.1
      to_state: 'off'
    - platform: 'state'
      entity_id: binary_sensor.window_bad_contact
      prob_given_true: 0.2
      prob_given_false: 0.3
      to_state: 'on'
    - platform: 'state'
      entity_id: binary_sensor.bathroom_dusche_last1
      prob_given_true: 0.90
      prob_given_false: 0.1
      to_state: 'on'
