  name: 'Baynesian Flur'
  platform: 'bayesian'
  prior: 0.60
  probability_threshold: 0.85
  observations:
    - platform: 'state'
      entity_id: binary_sensor.fl_motion_occupancy
      prob_given_true: 0.90
      prob_given_false: 0.1
      to_state: 'on'
    - platform: 'state'
      entity_id: binary_sensor.door_apartment_contact
      prob_given_true: 0.90
      prob_given_false: 0.1
      to_state: 'on'