  name: 'Baynesian Wohnzimmer'
  platform: 'bayesian'
  prior: 0.55
  probability_threshold: 0.85
  observations:
    - platform: 'state'
      entity_id: binary_sensor.shield_cam_person
      prob_given_true: 0.90
      prob_given_false: 0.05
      to_state: 'on'
    - platform: 'state'
      entity_id: binary_sensor.wz_motion_occupancy
      prob_given_true: 0.90
      prob_given_false: 0.05
      to_state: 'on'
    - platform: 'state'
      entity_id: media_player.onkyo_receiver
      prob_given_true: 0.8
      prob_given_false: 0.2
      to_state: 'on'
    - platform: 'state'
      entity_id: media_player.shield_tv
      prob_given_true: 0.9
      prob_given_false: 0.1
      to_state: 'playing'
    - platform: 'state'
      entity_id: media_player.shield_tv
      prob_given_true: 0.8
      prob_given_false: 0.2
      to_state: 'idle'
    - platform: 'state'
      entity_id: input_boolean.besuch
      prob_given_true: 0.9
      prob_given_false: 0.1
      to_state: 'on'