  name: 'Baynesian Arbeitszimmer'
  platform: 'bayesian'
  prior: 0.60
  probability_threshold: 0.85
  observations:
    - platform: 'state'
      entity_id: binary_sensor.az_motion_occupancy
      prob_given_true: 0.90
      prob_given_false: 0.1
      to_state: 'on'
    - platform: 'numeric_state'
      entity_id: 'sensor.pc_idle_time'
      prob_given_true: 0.8
      prob_given_false: 0.2
      below: '1500'
    - platform: 'state'
      entity_id: input_boolean.gaming
      prob_given_true: 0.80
      prob_given_false: 0.2
      to_state: 'on'

      