platform: emby_upcoming_media
api_key: !secret emby_token
user_id: !secret emby_id
host: !secret emby_host
port: !secret emby_port
ssl: true
max: 5
use_backdrop: false
include:
  - Movies
  - TV Shows
